import {
  DashboardData,
  NFTCTR,
  Order,
  ServiceArea,
  ServiceRequest,
  Supplier,
} from "./types";
import { generateCTRHash } from "./hash";
import { generateMockSolanaProof } from "./solana";

const serviceAddress = "Rua Augusta, 1500 — São Paulo, SP";

export const serviceAreas: ServiceArea[] = [
  {
    id: "SA-001",
    name: "Central São Paulo",
    city: "São Paulo",
    state: "SP",
    neighborhoods: ["Consolação", "Jardins", "Bela Vista", "Pinheiros"],
    coverageLabel: "Rua Augusta, Consolação and nearby construction sites",
  },
  {
    id: "SA-002",
    name: "Greater São Paulo East",
    city: "São Paulo",
    state: "SP",
    neighborhoods: ["Tatuapé", "Mooca", "Penha"],
    coverageLabel: "East-side commercial and residential construction areas",
  },
  {
    id: "SA-003",
    name: "Metropolitan West",
    city: "Osasco",
    state: "SP",
    neighborhoods: ["Centro", "Presidente Altino", "Vila Yara"],
    coverageLabel: "Osasco and western metropolitan construction corridors",
  },
];

export const demoServiceRequest: ServiceRequest = {
  id: "REQ-0001",
  address: "Rua Augusta, 1500",
  city: "São Paulo",
  state: "SP",
  neighborhood: "Consolação",
  wasteType: "CONSTRUCTION_DEBRIS",
  containerSize: "5m³",
  requestedDelivery: "Tomorrow morning",
  serviceAreaId: "SA-001",
};

export const suppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "EcoWaste Solutions",
    region: "Central São Paulo",
    price: 750,
    availableContainers: 8,
    rating: 4.8,
    verified: true,
    licenseNumber: "LIC-EW-2024-001",
    complianceScore: 96,
    deliveryTimeEstimate: "Tomorrow morning",
    distance: "2.4 km",
    serviceAreaIds: ["SA-001"],
  },
  {
    id: "SUP-002",
    name: "GreenBuild Logistics",
    region: "Central São Paulo",
    price: 690,
    availableContainers: 5,
    rating: 4.6,
    verified: true,
    licenseNumber: "LIC-GB-2024-002",
    complianceScore: 93,
    deliveryTimeEstimate: "Tomorrow afternoon",
    distance: "4.1 km",
    serviceAreaIds: ["SA-001", "SA-002"],
  },
  {
    id: "SUP-003",
    name: "Recicla Obra Express",
    region: "Central São Paulo",
    price: 820,
    availableContainers: 4,
    rating: 4.9,
    verified: true,
    licenseNumber: "LIC-RO-2024-003",
    complianceScore: 98,
    deliveryTimeEstimate: "Within 24 hours",
    distance: "3.6 km",
    serviceAreaIds: ["SA-001"],
  },
  {
    id: "SUP-004",
    name: "Caçambas Zona Oeste",
    region: "Central São Paulo",
    price: 640,
    availableContainers: 11,
    rating: 4.4,
    verified: true,
    licenseNumber: "LIC-CZO-2024-004",
    complianceScore: 89,
    deliveryTimeEstimate: "Tomorrow afternoon",
    distance: "5.7 km",
    serviceAreaIds: ["SA-001", "SA-003"],
  },
  {
    id: "SUP-005",
    name: "Ambiental CTR Log",
    region: "Central São Paulo",
    price: 890,
    availableContainers: 6,
    rating: 4.9,
    verified: true,
    licenseNumber: "LIC-ACTR-2024-005",
    complianceScore: 99,
    deliveryTimeEstimate: "Same day priority",
    distance: "6.2 km",
    serviceAreaIds: ["SA-001", "SA-002"],
  },
  {
    id: "SUP-006",
    name: "Construciclo Transportes",
    region: "Metropolitan West",
    price: 780,
    availableContainers: 7,
    rating: 4.7,
    verified: true,
    licenseNumber: "LIC-CT-2024-006",
    complianceScore: 94,
    deliveryTimeEstimate: "Within 24 hours",
    distance: "12.8 km",
    serviceAreaIds: ["SA-003", "SA-001"],
  },
];

export const demoOrder: Order = {
  id: "ORD-0001",
  customerName: "BuildRight Construction",
  customerAddress: serviceAddress,
  serviceAreaId: demoServiceRequest.serviceAreaId,
  supplierId: "SUP-001",
  supplierName: "EcoWaste Solutions",
  wasteType: demoServiceRequest.wasteType,
  containerSize: demoServiceRequest.containerSize,
  price: 750,
  platformFee: 45,
  status: "NFT_CTR_ISSUED",
  createdAt: "2026-04-25T10:00:00Z",
  destinationFacility: "Licensed Circular Recovery Facility",
  destinationAddress: "Av. do Estado, 4500 — São Paulo, SP",
  trackingEvents: [
    {
      id: "EVT-001",
      orderId: "ORD-0001",
      event: "ORDER_CREATED",
      title: "Order Created",
      description:
        "Customer submitted a demo container request for a construction site.",
      timestamp: "2026-04-25T10:00:00Z",
      location: "CAÇAMBAR request flow",
      validatedBy: "customer",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-002",
      orderId: "ORD-0001",
      event: "SUPPLIER_ASSIGNED",
      title: "Supplier Assigned",
      description:
        "EcoWaste Solutions was selected based on service area, availability and compliance score.",
      timestamp: "2026-04-25T10:15:00Z",
      location: "Central São Paulo service area",
      validatedBy: "platform",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-003",
      orderId: "ORD-0001",
      event: "CONTAINER_IN_TRANSIT",
      title: "Container In Transit",
      description:
        "Empty 5m³ container dispatched to the customer construction site.",
      timestamp: "2026-04-26T08:20:00Z",
      location: "Supplier depot",
      validatedBy: "supplier",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-004",
      orderId: "ORD-0001",
      event: "CONTAINER_DELIVERED",
      title: "Container Delivered",
      description: "Container delivered at Rua Augusta, 1500 and ready for use.",
      timestamp: "2026-04-26T09:40:00Z",
      location: serviceAddress,
      validatedBy: "supplier",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-005",
      orderId: "ORD-0001",
      event: "PICKUP_REQUESTED",
      title: "Pickup Requested",
      description:
        "Customer requested pickup after filling the container with construction debris.",
      timestamp: "2026-04-28T16:05:00Z",
      location: serviceAddress,
      validatedBy: "customer",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-006",
      orderId: "ORD-0001",
      event: "CONTAINER_COLLECTED",
      title: "Container Collected",
      description: "Full container collected from the construction site.",
      timestamp: "2026-04-29T09:20:00Z",
      location: serviceAddress,
      validatedBy: "supplier",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-007",
      orderId: "ORD-0001",
      event: "TRANSPORT_TO_DESTINATION",
      title: "Transport To Destination Facility",
      description: "Waste transported to a licensed circular recovery facility.",
      timestamp: "2026-04-29T10:00:00Z",
      location: "São Paulo, SP",
      validatedBy: "tracking_system",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-008",
      orderId: "ORD-0001",
      event: "DESTINATION_RECEIVED_WASTE",
      title: "Destination Facility Received Waste",
      description:
        "Licensed facility received the container and logged the inbound record.",
      timestamp: "2026-04-29T11:15:00Z",
      location: "Licensed Circular Recovery Facility",
      validatedBy: "destination_partner",
      layer: "CAÇAMBAR",
    },
    {
      id: "EVT-009",
      orderId: "ORD-0001",
      event: "FINAL_DESTINATION_VALIDATED",
      title: "Final Destination Validated",
      description:
        "Destination record validated as part of the audit-ready lifecycle.",
      timestamp: "2026-04-29T11:20:00Z",
      location: "CYKLOS validation layer",
      validatedBy: "system",
      layer: "CYKLOS",
    },
    {
      id: "EVT-010",
      orderId: "ORD-0001",
      event: "CTR_HASH_GENERATED",
      title: "CTR Hash Generated",
      description:
        "Critical lifecycle data was converted into a CTR cryptographic fingerprint.",
      timestamp: "2026-04-29T11:24:00Z",
      location: "CYKLOS infrastructure",
      validatedBy: "system",
      layer: "CYKLOS",
    },
    {
      id: "EVT-011",
      orderId: "ORD-0001",
      event: "SOLANA_PROOF_CREATED",
      title: "Solana Mock Proof Created",
      description:
        "A simulated Solana proof was created for MVP demonstration.",
      timestamp: "2026-04-29T11:25:00Z",
      location: "Solana Devnet-ready proof layer",
      validatedBy: "solana_proof_layer",
      layer: "CYKLOS",
    },
    {
      id: "EVT-012",
      orderId: "ORD-0001",
      event: "NFT_CTR_ISSUED",
      title: "NFT-CTR Issued",
      description:
        "NFT-CTR compliance certificate issued after the complete lifecycle was validated.",
      timestamp: "2026-04-29T11:27:00Z",
      location: "CYKLOS certificate layer",
      validatedBy: "system",
      layer: "CYKLOS",
    },
  ],
};

const ctrHash = generateCTRHash(demoOrder);
const solanaProof = generateMockSolanaProof(ctrHash);

export const demoNFTCTR: NFTCTR = {
  id: "NFT-CTR-0001",
  orderId: demoOrder.id,
  name: `NFT-CTR for ${demoOrder.id}`,
  description:
    "Verifiable waste transport compliance certificate generated from the completed CAÇAMBAR lifecycle and prepared for CYKLOS public verification.",
  ctrHash,
  solanaSignature: solanaProof.signature,
  explorerUrl: solanaProof.explorerUrl,
  mintedAt: "2026-04-29T11:27:00Z",
  metadata: {
    orderId: demoOrder.id,
    wasteType: demoOrder.wasteType,
    supplierName: demoOrder.supplierName,
    serviceAddress: demoOrder.customerAddress,
    containerSize: demoOrder.containerSize,
    destination: demoOrder.destinationFacility,
    status: "Verified compliance certificate",
  },
};

export const demoDashboardData: DashboardData = {
  totalOrdersTracked: 1,
  verifiedLifecycleEvents: demoOrder.trackingEvents.length,
  ctrHashesGenerated: 1,
  nftCtrCertificatesIssued: 1,
  simulatedSolanaProofs: 1,
  complianceStatus: "Verified demo lifecycle",
  supplierPerformance: "96% compliance score",
  circularEconomyMetric:
    "5m³ construction debris routed to licensed destination",
};